services:
  frontend:
    image: gitea.honya.dev/honya-dev-minilog/minilog-admin:latest
    container_name: minilog-admin
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minilog-admin.rule=Host(`minilog-admin.honya.dev`)"
      - "traefik.http.routers.minilog-admin.entrypoints=internal"
      - "traefik.http.services.minilog-admin.loadbalancer.server.port=8098"

networks:
  traefik:
    external: true
